#
# SConstruct for himan-plugins

Import('env')
import os
import sys

libcudart = '/opt/cuda/lib64/libcudart.so'

have_cuda = False

if os.path.isfile(libcudart):
	have_cuda = True


auxiliary_plugins = ['cache','fetcher','grib','neons','pcuda','querydata','writer']

compiled_plugins = ['dewpoint','icing', 'kindex', 'precipitation', 'seaicing', 'windvector']

cuda_plugins = ['tk2tc','tpot','vvms']

if have_cuda:
	env.Tool('cuda')

else:
	compiled_plugins.extend(cuda_plugins)

for p in auxiliary_plugins:

	file = 'source/' + p + '.cpp'
	env.SharedLibrary(target = p, source = [file])

for p in compiled_plugins:

	file = 'source/' + p + '.cpp'
	base = 'source/compiled_plugin_base.cpp'

	files = [file, base]

	env.SharedLibrary(target = p, source = files)

if have_cuda:
	for p in cuda_plugins:

		file = 'source/' + p + '.cpp'
		base = 'source/compiled_plugin_base.cpp'
		cufile = 'source/' + p + '_cuda.cu'
 
		files = [file, base, cufile]

		env.SharedLibrary(target = p, source = files)

