#
# SConstruct for himan-lib

Import('env')
import os

objects = []

for file in Glob('source/*.cpp'):
        s=os.path.basename(str(file))
        obj='obj/'+ s.replace(".cpp","")
	objects += env.SharedObject(obj, file)

lib = env.SharedLibrary(directory = 'lib', target = 'himan', source = objects)

env.Install(dir = '/usr/lib64', source = lib)
