import os
import platform

SConscript("scons_common.py")

Import('env build_dir')

# Includes

includes = []
includes.append('/usr/include/gdal')

env.Append(CPPPATH = includes)

# Library paths

librarypaths = []

librarypaths.append('/usr/lib64')
env.Append(LIBPATH = librarypaths)

# Libraries

libraries = []

libraries.append('fmidb')
libraries.append('dl')
libraries.append('pqxx')
libraries.append('boost_iostreams')
libraries.append('boost_filesystem')
libraries.append('boost_regex')
libraries.append('eccodes')
libraries.append('gdal')

if env['HAVE_S3']:
	libraries.append('s3')

env.Append(LIBS = libraries)
env.Append(LINKFLAGS = ['-rdynamic','-Wl,--as-needed'])
env.Append(NVCCFLAGS = ['--expt-extended-lambda', '--expt-relaxed-constexpr'])

SConscript('SConscript', exports = ['env'], variant_dir=build_dir, duplicate=0)
Clean('.', build_dir)
