import os
import platform

SConscript("scons_common.py")

Import('env build_dir')

# Library paths

librarypaths = []

if env['RELEASE']:
	librarypaths.append(env['WORKSPACE'] + '/himan-lib/build/release')
else:
	librarypaths.append(env['WORKSPACE'] + '/himan-lib/build/debug')

env.Append(LIBPATH = librarypaths)

# Libraries

libraries = []

libraries.append('himan')
libraries.append('fmidb')
libraries.append('pqxx')
libraries.append('boost_program_options')
libraries.append('boost_system')

env.Append(LIBS = libraries)
env.Append(LIBS = [ 'dl', 'rt' ]) # for cudart_static

# CFLAGS

env.Append(CCFLAGS = ['-fPIC', '-fPIE'])

# Linker flags

env.Append(LINKFLAGS = ['-rdynamic','-Wl,--warn-unresolved-symbols','-Wl,--as-needed' ,'-pthread', '-pie'])

SConscript('SConscript', exports = ['env'], variant_dir=build_dir, duplicate=0)
Clean('.', build_dir)
